driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/mct']

provisioner:
  require_chef_omnibus: 11.8.0

platforms:
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: debian-7.4
    run_list: apt::default
  - name: centos-5.10
  - name: centos-6.5
  - name: ubuntu-14.04-i386
    run_list: apt::default
  - name: ubuntu-12.04-i386
    run_list: apt::default
  - name: centos-5.10-i386
  - name: centos-6.5-i386
  - name: debian-7.4-i386
    run_list: apt::default

suites:
  - name: default
    run_list: omnibus::default
    attributes:
      omnibus:
        build_user:  vagrant
        build_dir:   /home/vagrant/mct
        install_dir: /opt/mct
